import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

const API = 'http://localhost:8000/api/v1/inventory';

type LotColumnKey='img'|'code'|'product'|'purchase'|'motor'|'location'|'stock'|'cost'|'flags'|'import'|'trace'|'notes'|'actions';
type Col={key:LotColumnKey;label:string;default:boolean;sort?:string};
const COLUMNS:Col[]=[
  {key:'img',label:'Imagen',default:true},{key:'code',label:'Lote',default:true,sort:'lot_code'},{key:'product',label:'Producto/SKU',default:true},{key:'purchase',label:'Compra/Proveedor',default:true},
  {key:'motor',label:'Motor',default:true},{key:'location',label:'Ubicación',default:true},{key:'stock',label:'Existencias',default:true},{key:'cost',label:'Costos',default:true},
  {key:'flags',label:'Estado',default:true},{key:'import',label:'Importación',default:false},{key:'trace',label:'Trazabilidad',default:false},{key:'notes',label:'Notas',default:false},{key:'actions',label:'Acciones',default:true}
];

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-header inventory-hero">
  <div><span class="eyebrow">🏷️ Inventario · Lotes</span><h1>Lotes</h1><p>CRUD principal con código automático por categoría, compra/proveedor, importación para motores y control físico/contable.</p></div>
  <div class="hero-actions"><button class="btn" (click)="loadAll()">🔄 Actualizar</button><button class="btn" (click)="exportCsv()">📤 CSV</button><button class="btn" (click)="openConfig.set(!openConfig())">⚙️ Columnas</button><button class="btn primary wide-auto" (click)="newLot()">➕ Nuevo lote</button></div>
</div>
<section class="alert-card"><strong>Regla protegida:</strong> la condición vive en Producto. El lote controla existencias, costo, trazabilidad, número motor, compra y ubicación.</section>
<section class="metric-grid pro-metrics"><article class="metric"><span>🏷️ Lotes</span><strong>{{lots().length}}</strong></article><article class="metric"><span>📦 Físico</span><strong>{{total('physical_qty')}}</strong></article><article class="metric"><span>🧮 Contable</span><strong>{{total('accounting_qty')}}</strong></article><article class="metric"><span>✅ Disponible</span><strong>{{total('available_physical')}}</strong></article><article class="metric"><span>🚫 Fuera contable</span><strong>{{outAccountingCount()}}</strong></article></section>
<section class="card" *ngIf="openConfig()"><div class="table-header"><div><h3>⚙️ Columnas visibles</h3><p class="muted">Configuración local de Lotes.</p></div><button class="btn" (click)="resetColumns()">Restablecer</button></div><div class="column-grid"><label class="check pill" *ngFor="let c of columns"><input type="checkbox" [checked]="visible()[c.key]" (change)="toggleColumn(c.key)"> {{c.label}}</label></div></section>
<section class="card">
  <div class="filters-row extended-filters"><input [(ngModel)]="search" placeholder="Buscar lote, SKU, producto, motor, proveedor, póliza..."/><select [(ngModel)]="mainCategoryFilter"><option value="">Categoría principal</option><option *ngFor="let c of mainCategories()" [value]="c.id">{{c.name}}</option></select><select [(ngModel)]="productCategoryFilter"><option value="">Categoría producto</option><option *ngFor="let c of productCategories()" [value]="c.id">{{c.name}}</option></select><select [(ngModel)]="brandFilter"><option value="">Marca</option><option *ngFor="let b of brands()" [value]="b.id">{{b.name}}</option></select><select [(ngModel)]="seriesFilter"><option value="">Serie</option><option *ngFor="let s of series()" [value]="s.id">{{s.code}}</option></select><select [(ngModel)]="quick"><option value="">Todos</option><option value="fuera_contable">Fuera contable</option><option value="bloqueado">Bloqueado</option><option value="desarmable">Desarmable</option><option value="sin_motor">Sin motor</option><option value="danado">Dañados</option><option value="reparacion">En reparación</option></select><button class="btn" (click)="clearFilters()">🧹 Limpiar</button></div>
  <div class="table-wrap ultra-wide-table"><table><thead><tr><th *ngIf="isVisible('img')">Imagen</th><th *ngIf="isVisible('code')" (click)="sortBy('lot_code')">Lote {{sortIcon('lot_code')}}</th><th *ngIf="isVisible('product')">Producto</th><th *ngIf="isVisible('purchase')">Compra</th><th *ngIf="isVisible('motor')">Motor/Serie</th><th *ngIf="isVisible('location')">Ubicación</th><th *ngIf="isVisible('stock')">Existencias</th><th *ngIf="isVisible('cost')">Costo</th><th *ngIf="isVisible('flags')">Estado</th><th *ngIf="isVisible('import')">Importación</th><th *ngIf="isVisible('trace')">Trazabilidad</th><th *ngIf="isVisible('notes')">Notas</th><th *ngIf="isVisible('actions')">Acciones</th></tr></thead><tbody>
    <tr *ngFor="let l of filteredLots()" (click)="selected.set(l)" [class.selected]="selected()?.id===l.id"><td *ngIf="isVisible('img')" class="sticky-img"><div class="thumb">{{isMotor(l)?'🚗':'🏷️'}}</div></td><td *ngIf="isVisible('code')"><strong>{{l.lot_code}}</strong><br><small>{{l.barcode||'Sin barras'}} · {{l.qr_code||'QR pendiente'}}</small></td><td *ngIf="isVisible('product')"><strong>{{product(l.product_id)?.sku}}</strong><br>{{product(l.product_id)?.name}}<br><small>{{categoryName(product(l.product_id)?.product_category_id)}} · {{product(l.product_id)?.condition}}</small></td><td *ngIf="isVisible('purchase')">{{l.purchase_document_reference||purchase(l.purchase_id)?.purchase_code||'Manual'}}<br><strong>{{l.supplier_name||purchase(l.purchase_id)?.supplier_name||'Sin proveedor'}}</strong><br><small>{{l.purchase_date||'Fecha manual'}}</small></td><td *ngIf="isVisible('motor')">No. motor: <strong>{{l.engine_number||'—'}}</strong><br>Serie: {{seriesName(product(l.product_id)?.engine_series_id)}}<br><small>{{product(l.product_id)?.fuel_type}} · {{product(l.product_id)?.displacement_cc}}cc</small></td><td *ngIf="isVisible('location')">{{warehouse(l.warehouse_id)}}<br><strong>{{l.location||'Sin ubicación'}}</strong></td><td *ngIf="isVisible('stock')">Físico <strong>{{l.physical_qty}}</strong><br>Contable <strong>{{l.accounting_qty}}</strong><br>Disponible <strong>{{l.available_physical}}</strong><br><small>Reservado {{l.reserved_qty}} · Pendiente {{l.pending_exit_qty}}</small></td><td *ngIf="isVisible('cost')">Unitario <strong>Q {{money(l.unit_cost)}}</strong><br><small>IVA incluido: {{l.cost_includes_tax?'sí':'no'}}</small></td><td *ngIf="isVisible('flags')"><span class="status-pill" [class.status-ok]="Number(l.available_physical)>0">{{l.inventory_status}}</span><br><span class="chip soft" *ngIf="l.is_out_of_accounting_inventory">Fuera contable</span> <span class="chip soft" *ngIf="l.is_disassemblable">Desarmable</span> <span class="chip soft" *ngIf="l.is_blocked">Bloqueado</span></td><td *ngIf="isVisible('import')">{{l.import_policy_number||'—'}}<br><small>{{l.import_port||'—'}} · {{l.import_date||'—'}}</small></td><td *ngIf="isVisible('trace')">ID {{l.id}} · Padre {{l.parent_lot_id||'—'}}<br><small>Desarme {{l.disassembly_status}}</small></td><td *ngIf="isVisible('notes')"><small>{{l.notes||'—'}}</small></td><td *ngIf="isVisible('actions')"><button class="btn small" (click)="$event.stopPropagation(); editLot(l)">✏️</button><button class="btn small" (click)="$event.stopPropagation(); duplicateLot(l)">⧉</button></td></tr>
  </tbody></table></div>
</section>
<section class="detail-drawer card" *ngIf="selected() && !drawerOpen()"><div class="table-header"><div><h3>📌 Contexto de lote</h3><p class="muted">{{selected()?.lot_code}} · {{product(selected()?.product_id)?.name}}</p></div><button class="btn" (click)="selected.set(null)">Cerrar</button></div><div class="quick-actions"><button class="btn" (click)="editLot(selected())">✏️ Editar</button><a class="btn" href="/multimedia">📷 Fotos/QR</a><a class="btn" href="/automotive">🚗 Automotriz</a><a class="btn" href="/purchases">📥 Compra</a></div></section>
<div class="drawer-backdrop" *ngIf="drawerOpen()" (click)="closeDrawer()"></div>
<aside class="product-drawer" *ngIf="drawerOpen()"><div class="drawer-head"><div><h2>{{editingId?'Editar lote':'Nuevo lote'}}</h2><p>Lote con código automático por categoría y trazabilidad.</p></div><button class="btn icon" (click)="closeDrawer()">×</button></div><div class="drawer-tabs"><button *ngFor="let t of tabs" [class.active]="tab()===t.key" (click)="tab.set(t.key)">{{t.label}}</button></div><div class="drawer-body">
  <section *ngIf="tab()==='general'"><h3>🏷️ General</h3><div class="form-grid"><label>Producto<div class="inline-add"><select [(ngModel)]="form.product_id" (change)="onProductChange()"><option [ngValue]="null">—</option><option *ngFor="let p of products()" [ngValue]="p.id">{{p.sku}} · {{p.name}}</option></select><a class="btn small" href="/inventory/products">＋</a></div></label><label>SKU producto<input [ngModel]="product(form.product_id)?.sku||''" readonly></label><label>Código lote<input [(ngModel)]="form.lot_code" (input)="autoCodes()" placeholder="Automático si queda vacío"></label><label>Cantidad inicial<input type="number" [(ngModel)]="form.quantity_initial" (input)="syncQuantities()"></label><label>Costo obligatorio<input type="number" [(ngModel)]="form.unit_cost"></label></div>
    <div class="section-title">Compra y proveedor</div><div class="form-grid"><label>Documento compra<select [(ngModel)]="form.purchase_id" (change)="applyPurchase()"><option [ngValue]="null">Manual / sin compra</option><option *ngFor="let p of purchases()" [ngValue]="p.id">{{p.purchase_code}} · {{p.supplier_name}}</option></select></label><label>Proveedor<input [(ngModel)]="form.supplier_name" placeholder="Obligatorio si no hay compra"></label><label>NIT proveedor<input [(ngModel)]="form.supplier_tax_id"></label><label>Referencia compra<input [(ngModel)]="form.purchase_document_reference"></label><label>Fecha compra<input type="date" [(ngModel)]="form.purchase_date"></label><label>Bodega<select [(ngModel)]="form.warehouse_id"><option [ngValue]="null">Central por defecto</option><option *ngFor="let w of warehouses()" [ngValue]="w.id">{{w.code}} · {{w.name}}</option></select></label><label>Ubicación<input [(ngModel)]="form.location" placeholder="Estantería / pasillo"></label></div><button class="btn" (click)="createDraftPurchase()">📥 Crear compra borrador aquí</button>
    <div class="section-title" *ngIf="isMotorForm()">Motor e importación</div><div class="form-grid" *ngIf="isMotorForm()"><label>Número motor *<input [(ngModel)]="form.engine_number" placeholder="Único y obligatorio para motores"></label><label>Póliza<input [(ngModel)]="form.import_policy_number"></label><label>Puerto<input [(ngModel)]="form.import_port"></label><label>Fecha importación<input type="date" [(ngModel)]="form.import_date"></label></div>
    <div class="section-title">Trazabilidad automática</div><div class="form-grid"><label>Código barras<input [(ngModel)]="form.barcode" placeholder="Automático = código lote"></label><label>QR<input [(ngModel)]="form.qr_code" placeholder="Automático = ERP:LOT:código"></label></div>
    <div class="section-title">Notas</div><label>Comentarios internos<textarea [(ngModel)]="form.notes"></textarea></label>
  </section>
  <section *ngIf="tab()==='stock'"><h3>🔒 Stock protegido</h3><p class="muted">La cantidad inicial alimenta físico y contable. Si el lote está fuera de inventario contable, contable inicial queda en 0.</p><div class="form-grid"><label>Físico inicial<input type="number" [(ngModel)]="form.physical_initial_qty" readonly></label><label>Contable inicial<input type="number" [(ngModel)]="form.accounting_initial_qty" readonly></label><label>Estado<select [(ngModel)]="form.inventory_status"><option value="disponible">Disponible</option><option value="danado">Dañado</option><option value="reparacion">En reparación</option><option value="bloqueado">Bloqueado</option><option value="pendiente_facturar">Pendiente facturar</option></select></label></div><div class="switch-row switch-row-pro"><label class="switch-pill"><input type="checkbox" [(ngModel)]="form.cost_includes_tax"><span>Costo incluye IVA</span></label><label class="switch-pill"><input type="checkbox" [(ngModel)]="form.is_out_of_accounting_inventory" (change)="syncQuantities()"><span>Fuera inventario contable</span></label><label class="switch-pill"><input type="checkbox" [(ngModel)]="form.is_sellable"><span>Vendible</span></label><label class="switch-pill"><input type="checkbox" [(ngModel)]="form.is_blocked"><span>Bloqueado</span></label><label class="switch-pill"><input type="checkbox" [(ngModel)]="form.is_disassemblable"><span>Desarmable</span></label></div></section>
</div><div class="drawer-footer"><button class="btn" (click)="closeDrawer()">Cancelar</button><button class="btn primary wide-auto" (click)="saveLot()">💾 Guardar</button></div></aside>
`})
export class InventoryLotsComponent{
  private http=inject(HttpClient); products=signal<any[]>([]); lots=signal<any[]>([]); warehouses=signal<any[]>([]); categories=signal<any[]>([]); brands=signal<any[]>([]); series=signal<any[]>([]); purchases=signal<any[]>([]);
  selected=signal<any|null>(null); drawerOpen=signal(false); openConfig=signal(false); tab=signal('general'); columns=COLUMNS; visible=signal<Record<LotColumnKey,boolean>>(this.readColumns());
  search=''; mainCategoryFilter=''; productCategoryFilter=''; brandFilter=''; seriesFilter=''; quick=''; sortKey='lot_code'; sortDir:1|-1=1; editingId:number|null=null; form:any=this.blank(); tabs=[{key:'general',label:'🏷️ General'},{key:'stock',label:'🔒 Stock protegido'}];
  mainCategories=computed(()=>this.categories().filter(c=>c.category_kind==='principal')); productCategories=computed(()=>this.categories().filter(c=>c.category_kind!=='principal'));
  filteredLots=computed(()=>{const term=this.search.trim().toLowerCase();let rows=this.lots().filter(l=>{const p=this.product(l.product_id);const txt=[l.lot_code,l.barcode,l.qr_code,l.engine_number,l.location,l.inventory_status,l.supplier_name,l.import_policy_number,l.notes,p?.sku,p?.name,p?.oem_primary,this.categoryName(p?.main_category_id),this.categoryName(p?.product_category_id),this.seriesName(p?.engine_series_id)].join(' ').toLowerCase();if(term&&!txt.includes(term))return false;if(this.mainCategoryFilter&&String(p?.main_category_id)!==String(this.mainCategoryFilter))return false;if(this.productCategoryFilter&&String(p?.product_category_id||p?.category_id)!==String(this.productCategoryFilter))return false;if(this.brandFilter&&String(p?.brand_id)!==String(this.brandFilter))return false;if(this.seriesFilter&&String(p?.engine_series_id)!==String(this.seriesFilter))return false;if(this.quick==='fuera_contable'&&!l.is_out_of_accounting_inventory)return false;if(this.quick==='bloqueado'&&!(l.is_blocked||l.inventory_status==='bloqueado'))return false;if(this.quick==='desarmable'&&!l.is_disassemblable)return false;if(this.quick==='sin_motor'&&(l.engine_number||'').trim())return false;if(this.quick==='danado'&&l.inventory_status!=='danado')return false;if(this.quick==='reparacion'&&l.inventory_status!=='reparacion')return false;return true;});return rows.sort((a,b)=>String(a[this.sortKey]??'').localeCompare(String(b[this.sortKey]??''),undefined,{numeric:true})*this.sortDir);});
  constructor(){this.loadAll();}
  loadAll(){this.http.get<any[]>(`${API}/products`).subscribe(v=>{this.products.set(v);this.prefillFromStorage();});this.http.get<any[]>(`${API}/lots`).subscribe(v=>this.lots.set(v));this.http.get<any[]>(`${API}/warehouses`).subscribe(v=>this.warehouses.set(v));this.http.get<any[]>(`${API}/categories`).subscribe(v=>this.categories.set(v));this.http.get<any[]>(`${API}/brands`).subscribe(v=>this.brands.set(v));this.http.get<any[]>(`${API}/engine-series`).subscribe(v=>this.series.set(v));this.http.get<any[]>(`${API}/purchases`).subscribe(v=>this.purchases.set(v));}
  blank(){return{product_id:null,warehouse_id:null,lot_code:'',barcode:'',qr_code:'',engine_number:'',serial_number:'',location:'',quantity_initial:1,physical_initial_qty:1,accounting_initial_qty:1,unit_cost:0,cost_includes_tax:true,is_out_of_accounting_inventory:false,is_sellable:true,is_blocked:false,inventory_status:'disponible',is_disassemblable:false,disassembly_status:'no_aplica',parent_lot_id:null,purchase_id:null,purchase_document_reference:'',purchase_date:this.today(),supplier_name:'',supplier_tax_id:'',import_policy_number:'',import_port:'',import_date:'',notes:''};}
  today(){return new Date().toISOString().slice(0,10);} newLot(){this.editingId=null;this.form=this.blank();this.tab.set('general');this.drawerOpen.set(true);this.syncQuantities();} editLot(l:any){this.editingId=l.id;this.form={...this.blank(),...l};this.tab.set('general');this.drawerOpen.set(true);this.syncQuantities(false);} duplicateLot(l:any){this.editingId=null;this.form={...this.blank(),...l,id:undefined,lot_code:'',barcode:'',qr_code:'',engine_number:''};this.drawerOpen.set(true);this.onProductChange();} closeDrawer(){this.drawerOpen.set(false);} 
  saveLot(){this.syncQuantities();this.autoCodes();if(!this.form.product_id){alert('Selecciona producto');return;} if(this.isMotorForm()&&!String(this.form.engine_number||'').trim()){alert('Número motor obligatorio para categoría Motor');return;} if(Number(this.form.unit_cost||0)<=0){alert('El costo es obligatorio');return;} const req=this.editingId?this.http.put(`${API}/lots/${this.editingId}`,this.form):this.http.post(`${API}/lots`,this.form);req.subscribe({next:()=>{this.loadAll();this.closeDrawer();},error:e=>alert(e?.error?.detail||'No se pudo guardar lote')});}
  onProductChange(){if(!this.form.product_id)return; this.http.get<any>(`${API}/lots/code-preview/${this.form.product_id}`).subscribe(v=>{if(!this.editingId&&!this.form.lot_code){this.form.lot_code=v.next_code;this.autoCodes();}});this.syncQuantities();}
  applyPurchase(){const p=this.purchase(this.form.purchase_id); if(!p)return; this.form.supplier_name=p.supplier_name; this.form.supplier_tax_id=p.supplier_tax_id; this.form.purchase_document_reference=p.document_reference||p.purchase_code; this.form.purchase_date=this.form.purchase_date||this.today();}
  createDraftPurchase(){if(!this.form.product_id){alert('Selecciona producto primero');return;} const payload={supplier_name:this.form.supplier_name||'Proveedor general',supplier_tax_id:this.form.supplier_tax_id||'CF',status:'borrador',document_reference:this.form.purchase_document_reference||'',notes:'Compra borrador creada desde lote',internal_notes:'',warehouse_id:this.form.warehouse_id,lines:[{product_id:this.form.product_id,warehouse_id:this.form.warehouse_id,lot_code:this.form.lot_code,quantity:this.form.quantity_initial||1,unit_cost_with_tax:this.form.unit_cost||0,is_out_of_accounting_inventory:this.form.is_out_of_accounting_inventory,notes:this.form.notes||''}]};this.http.post<any>(`${API}/purchases`,payload).subscribe({next:p=>{this.loadAll();this.form.purchase_id=p.id;this.applyPurchase();alert('Compra borrador creada. Puedes completarla en Compras Pro.');},error:e=>alert(e?.error?.detail||'No se pudo crear compra')});}
  prefillFromStorage(){const raw=localStorage.getItem('erp_prefill_lot_product');if(raw){try{const p=JSON.parse(raw);this.newLot();this.form.product_id=p.id;this.onProductChange();localStorage.removeItem('erp_prefill_lot_product');}catch{}}}
  isMotor(l:any){return this.isMotorProduct(this.product(l.product_id));} isMotorForm(){return this.isMotorProduct(this.product(this.form.product_id));} isMotorProduct(p:any){const cat=this.categoryName(p?.main_category_id).toLowerCase();return p?.product_type==='motor'||cat.includes('motor');}
  product(id:any){return this.products().find(p=>Number(p.id)===Number(id));} purchase(id:any){return this.purchases().find(p=>Number(p.id)===Number(id));} warehouse(id:any){const w=this.warehouses().find(x=>Number(x.id)===Number(id));return w?`${w.code} — ${w.name}`:'Sin bodega';} categoryName(id:any){return this.categories().find(c=>Number(c.id)===Number(id))?.name||'—';} seriesName(id:any){return this.series().find(s=>Number(s.id)===Number(id))?.code||'—';}
  outAccountingCount(){return this.lots().filter(l=>l.is_out_of_accounting_inventory).length;} total(k:string){return this.lots().reduce((a,l)=>a+Number(l[k]||0),0);} money(v:any){return Number(v||0).toFixed(2);} Number(v:any){return Number(v||0);} clearFilters(){this.search=this.mainCategoryFilter=this.productCategoryFilter=this.brandFilter=this.seriesFilter=this.quick='';} sortBy(k:string){if(this.sortKey===k)this.sortDir=this.sortDir===1?-1:1;else{this.sortKey=k;this.sortDir=1;}} sortIcon(k:string){return this.sortKey===k?(this.sortDir===1?'↑':'↓'):'';} isVisible(k:LotColumnKey){return !!this.visible()[k];} toggleColumn(k:LotColumnKey){const n={...this.visible(),[k]:!this.visible()[k]};this.visible.set(n);localStorage.setItem('erp_lots_columns',JSON.stringify(n));} resetColumns(){localStorage.removeItem('erp_lots_columns');this.visible.set(this.readColumns());} readColumns():Record<LotColumnKey,boolean>{try{const s=JSON.parse(localStorage.getItem('erp_lots_columns')||'{}');return Object.fromEntries(COLUMNS.map(c=>[c.key,s[c.key]??c.default])) as any;}catch{return Object.fromEntries(COLUMNS.map(c=>[c.key,c.default])) as any;}}
  autoCodes(){ if(this.form.lot_code){ this.form.lot_code=String(this.form.lot_code).toUpperCase(); this.form.barcode=this.form.barcode||this.form.lot_code; this.form.qr_code=this.form.qr_code||'ERP:LOT:'+this.form.lot_code; } }
  syncQuantities(overwrite=true){ const q=Number(this.form.quantity_initial||0); if(overwrite||this.form.physical_initial_qty==null)this.form.physical_initial_qty=q; if(overwrite||this.form.accounting_initial_qty==null)this.form.accounting_initial_qty=this.form.is_out_of_accounting_inventory?0:q; }
  exportCsv(){const h=['Lote','SKU','Producto','Motor','Proveedor','Fisico','Contable','Disponible','Costo','Estado','Poliza'];const rows=this.filteredLots().map(l=>[l.lot_code,this.product(l.product_id)?.sku,this.product(l.product_id)?.name,l.engine_number,l.supplier_name,l.physical_qty,l.accounting_qty,l.available_physical,l.unit_cost,l.inventory_status,l.import_policy_number]);this.download('lotes_detallados.csv',[h,...rows]);} download(name:string, rows:any[][]){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();}
}
