import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
const API='http://localhost:8000/api/v1/inventory';
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-header inventory-hero"><div><span class="eyebrow">🚘 Inventario · Marcas / Modelos</span><h1>Marcas y líneas/modelos</h1><p>Catálogo separado para compatibilidades, productos, series motor y futura sincronización WooCommerce.</p></div><div class="hero-actions"><button class="btn" (click)="load()">🔄 Actualizar</button><button class="btn primary wide-auto" (click)="saveBrand()">💾 Guardar marca</button></div></div>
<section class="grid-two"><article class="card"><h3>{{editingBrand?'✏️ Editar':'➕ Nueva'}} marca</h3><label>Nombre marca<input [(ngModel)]="brandForm.name" placeholder="Toyota, Mazda, Hyundai"></label><div class="quick-actions"><button class="btn" (click)="resetBrand()">Limpiar</button><button class="btn primary wide-auto" (click)="saveBrand()">Guardar marca</button></div><hr><h3>➕ Nuevo modelo/línea</h3><div class="form-grid"><label>Marca<select [(ngModel)]="modelForm.brand_id"><option [ngValue]="null">Seleccionar marca</option><option *ngFor="let b of brands()" [ngValue]="b.id">{{b.name}}</option></select></label><label>Línea/modelo<input [(ngModel)]="modelForm.name" placeholder="Hilux, H1, Porter, Sorento"></label></div><button class="btn" (click)="saveModel()">Guardar modelo/línea</button></article>
<article class="card"><div class="table-header"><div><h3>📚 Marcas registradas</h3><p class="muted">Click en una marca para ver sus modelos.</p></div><input [(ngModel)]="search" placeholder="Buscar marca o modelo..."></div><div class="table-wrap"><table><thead><tr><th (click)="sortBrand()">Marca {{brandSort===1?'↑':'↓'}}</th><th>Modelos / líneas</th><th>Acciones</th></tr></thead><tbody><tr *ngFor="let b of filteredBrands()" [class.selected]="selectedBrand()?.id===b.id" (click)="selectedBrand.set(b)"><td><strong>🚘 {{b.name}}</strong><br><small>{{b.is_active?'Activa':'Inactiva'}}</small></td><td><span class="chip" *ngFor="let m of modelsByBrand(b.id)">{{m.name}}</span><small *ngIf="!modelsByBrand(b.id).length">Sin modelos</small></td><td><button class="btn small" (click)="$event.stopPropagation(); editBrand(b)">✏️</button></td></tr></tbody></table></div></article></section>
`})
export class InventoryBrandsModelsComponent{private http=inject(HttpClient);brands=signal<any[]>([]);models=signal<any[]>([]);selectedBrand=signal<any|null>(null);search='';brandSort:1|-1=1;editingBrand:any=null;brandForm:any={name:''};modelForm:any={brand_id:null,name:''};constructor(){this.load();}load(){this.http.get<any[]>(`${API}/brands`).subscribe(v=>this.brands.set(v));this.http.get<any[]>(`${API}/vehicle-models`).subscribe(v=>this.models.set(v));}filteredBrands(){const q=this.search.toLowerCase().trim();return this.brands().filter(b=>!q||[b.name,...this.modelsByBrand(b.id).map(m=>m.name)].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)*this.brandSort);}modelsByBrand(id:any){return this.models().filter(m=>Number(m.brand_id)===Number(id));}sortBrand(){this.brandSort=this.brandSort===1?-1:1;}resetBrand(){this.editingBrand=null;this.brandForm={name:''};}editBrand(b:any){this.editingBrand=b;this.brandForm={...b};}saveBrand(){if(!this.brandForm.name){alert('Nombre requerido');return;}const req=this.editingBrand?this.http.put(`${API}/brands/${this.editingBrand.id}`,this.brandForm):this.http.post(`${API}/brands`,this.brandForm);req.subscribe({next:()=>{this.load();this.resetBrand();},error:e=>alert(e?.error?.detail||'No se pudo guardar marca')});}saveModel(){if(!this.modelForm.brand_id||!this.modelForm.name){alert('Selecciona marca e ingresa modelo/línea');return;}this.http.post(`${API}/vehicle-models`,this.modelForm).subscribe({next:()=>{this.load();this.modelForm={brand_id:this.modelForm.brand_id,name:''};},error:e=>alert(e?.error?.detail||'No se pudo guardar modelo')});}}
