import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
const API='http://localhost:8000/api/v1/inventory';

type CatalogType={key:string;label:string;hint:string;icon:string};
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-header inventory-hero"><div><span class="eyebrow">🧬 Inventario · Catálogos / Atributos</span><h1>Listas maestras</h1><p>CRUD completo para listas usadas en productos, series, lotes, compras y documentos. Marcas/modelos tienen página propia.</p></div><div class="hero-actions"><button class="btn" (click)="load()">🔄 Actualizar</button><a class="btn" href="/inventory/brands-models">🚘 Marcas / modelos</a><button class="btn primary wide-auto" (click)="saveValue()">💾 Guardar valor</button></div></div>
<section class="catalog-layout catalog-layout-pro"><aside class="card filter-panel"><h3>📚 Listas</h3><input [(ngModel)]="typeSearch" placeholder="Buscar lista..." class="full"><button class="chip-button" *ngFor="let t of filteredTypes()" [class.active]="selectedType()===t.key" (click)="selectedType.set(t.key); resetValue()">{{t.icon}} {{t.label}}</button></aside>
<article class="card catalog-table-card"><div class="table-header"><div><h3>{{label(selectedType())}}</h3><p class="muted">{{hint(selectedType())}}</p></div><input [(ngModel)]="search" placeholder="Buscar valor..."></div><div class="table-wrap"><table><thead><tr><th (click)="sortBy('name')">Nombre {{sortIcon('name')}}</th><th (click)="sortBy('code')">Código {{sortIcon('code')}}</th><th>Descripción</th><th (click)="sortBy('sort_order')">Orden {{sortIcon('sort_order')}}</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr *ngFor="let v of filteredValues()"><td><strong>{{v.name}}</strong></td><td><span class="chip">{{v.code||'—'}}</span></td><td>{{v.description||'—'}}</td><td>{{v.sort_order||0}}</td><td><span class="status-pill" [class.status-ok]="v.is_active" [class.status-void]="!v.is_active">{{v.is_active?'Activo':'Inactivo'}}</span></td><td><button class="btn small" (click)="editValue(v)">✏️</button></td></tr></tbody></table></div></article>
<aside class="card catalog-forms"><h3>{{editingValue?'✏️ Editar':'➕ Nuevo'}} valor</h3><label>Lista<select [(ngModel)]="valueForm.catalog_type"><option *ngFor="let t of types" [value]="t.key">{{t.label}}</option></select></label><label>Nombre<input [(ngModel)]="valueForm.name"></label><label>Código<input [(ngModel)]="valueForm.code" placeholder="Opcional / único dentro de la lista"></label><label>Orden<input type="number" [(ngModel)]="valueForm.sort_order"></label><label>Descripción<textarea [(ngModel)]="valueForm.description"></textarea></label><label class="switch-pill"><input type="checkbox" [(ngModel)]="valueForm.is_active"><span>Activo</span></label><div class="quick-actions"><button class="btn" (click)="resetValue()">Limpiar</button><button class="btn primary wide-auto" (click)="saveValue()">Guardar</button></div><hr><h3>✨ Características / tipos</h3><p class="muted">Usadas como chips en productos: Turbo, 4x4, DOHC, automático, etc.</p><label>Nombre característica<input [(ngModel)]="charForm.name" placeholder="Turbo, 4x4, DOHC"></label><label>Descripción<textarea [(ngModel)]="charForm.description"></textarea></label><button class="btn" (click)="saveCharacteristic()">＋ Guardar característica</button><div class="chip-list"><button class="chip" *ngFor="let c of characteristics()" (click)="editCharacteristic(c)">{{c.name}}</button></div></aside></section>
`})
export class InventoryAttributesComponent{private http=inject(HttpClient);types:CatalogType[]=[
{key:'combustible',label:'Combustibles',icon:'⛽',hint:'Diésel, Gasolina, Híbrido.'},{key:'cc',label:'C.C.',icon:'🔢',hint:'Cilindradas usadas por series y productos.'},{key:'cilindros',label:'Cilindros',icon:'⚙️',hint:'4, 6, 8...'}, {key:'condicion',label:'Condición producto',icon:'✅',hint:'Nuevo, usado, reparado.'},{key:'unidad',label:'Unidades',icon:'📏',hint:'Unidad, juego, kit, caja.'},{key:'tipo_producto',label:'Tipos de producto',icon:'🧩',hint:'Motor, repuesto, servicio, accesorio.'},{key:'ubicacion',label:'Ubicaciones',icon:'📍',hint:'Estantería, bodega, pasillo.'},{key:'puerto',label:'Puertos / importación',icon:'🚢',hint:'Puerto, aduana, naviera.'},{key:'transmision',label:'Transmisión',icon:'🕹️',hint:'Mecánica, automática.'},{key:'traccion',label:'Tracción',icon:'🚙',hint:'4x2, 4x4, FWD, RWD.'},{key:'estado_lote',label:'Estados de lote',icon:'🏷️',hint:'Disponible, dañado, reparación, bloqueado.'}
];selectedType=signal('combustible');values=signal<any[]>([]);characteristics=signal<any[]>([]);search='';typeSearch='';sortKey='name';sortDir:1|-1=1;editingValue:any=null;editingChar:any=null;valueForm:any=this.blankValue();charForm:any={name:'',description:''};filteredTypes=computed(()=>this.types.filter(t=>!this.typeSearch.trim()||t.label.toLowerCase().includes(this.typeSearch.toLowerCase())||t.key.includes(this.typeSearch.toLowerCase())));filteredValues=computed(()=>{const q=this.search.toLowerCase().trim();return this.values().filter(v=>v.catalog_type===this.selectedType()&&(!q||[v.name,v.code,v.description].join(' ').toLowerCase().includes(q))).sort((a,b)=>String(a[this.sortKey]??'').localeCompare(String(b[this.sortKey]??''),undefined,{numeric:true})*this.sortDir);});constructor(){this.load();}
blankValue(){return{catalog_type:this.selectedType(),name:'',code:'',description:'',sort_order:0,is_active:true};}load(){this.http.get<any[]>(`${API}/catalog-values`).subscribe(v=>this.values.set(v));this.http.get<any[]>(`${API}/characteristics`).subscribe(v=>this.characteristics.set(v));}label(k:string){return this.types.find(t=>t.key===k)?.label||k;}hint(k:string){return this.types.find(t=>t.key===k)?.hint||'';}resetValue(){this.editingValue=null;this.valueForm=this.blankValue();}editValue(v:any){this.editingValue=v;this.valueForm={...this.blankValue(),...v};}saveValue(){if(!this.valueForm.name){alert('Nombre requerido');return;} this.valueForm.catalog_type=this.valueForm.catalog_type||this.selectedType();const req=this.editingValue?this.http.put(`${API}/catalog-values/${this.editingValue.id}`,this.valueForm):this.http.post(`${API}/catalog-values`,this.valueForm);req.subscribe({next:()=>{this.load();this.resetValue();},error:e=>alert(e?.error?.detail||'No se pudo guardar valor')});}editCharacteristic(c:any){this.editingChar=c;this.charForm={...c};}saveCharacteristic(){if(!this.charForm.name){alert('Nombre requerido');return;} const req=this.editingChar?this.http.put(`${API}/characteristics/${this.editingChar.id}`,this.charForm):this.http.post(`${API}/characteristics`,this.charForm);req.subscribe({next:()=>{this.load();this.editingChar=null;this.charForm={name:'',description:''};},error:e=>alert(e?.error?.detail||'No se pudo guardar característica')});}sortBy(k:string){if(this.sortKey===k)this.sortDir=this.sortDir===1?-1:1;else{this.sortKey=k;this.sortDir=1;}}sortIcon(k:string){return this.sortKey===k?(this.sortDir===1?'↑':'↓'):'';}}
