import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
const API='http://localhost:8000/api/v1/inventory';
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-header inventory-hero"><div><span class="eyebrow">⚙️ Inventario · Series motor</span><h1>Series motor</h1><p>Catálogo inteligente que alimenta marca, combustible, C.C., cilindros, SKU y compatibilidades.</p></div><div class="hero-actions"><button class="btn" (click)="load()">🔄 Actualizar</button><button class="btn primary wide-auto" (click)="save()">💾 Guardar serie</button></div></div>
<section class="grid-two"><article class="card"><h3>{{editing?'✏️ Editar':'➕ Nueva'}} serie</h3><div class="form-grid"><label>Código<input [(ngModel)]="form.code" (ngModelChange)="onCodeChange()" placeholder="D4CB"></label><label>Nombre<input [(ngModel)]="form.name" placeholder="Automático = Código"></label><label>Marca relacionada<input [(ngModel)]="form.brand_name"></label><label>Combustible<input [(ngModel)]="form.fuel_type"></label><label>C.C.<input [(ngModel)]="form.displacement_cc"></label><label>Cilindros<input [(ngModel)]="form.cylinders"></label><label>Prefijo SKU<input [(ngModel)]="form.sku_prefix"></label><label>Equivalencias<textarea [(ngModel)]="form.equivalent_series"></textarea></label></div><div class="quick-actions"><button class="btn" (click)="reset()">Limpiar</button><button class="btn" (click)="autoFromCode()">✨ Automatizar desde código</button></div></article><article class="card"><input [(ngModel)]="search" placeholder="Buscar serie..." class="search-inline"><div class="table-wrap"><table><thead><tr><th>Serie</th><th>Datos</th><th>Automatización</th><th>Acciones</th></tr></thead><tbody><tr *ngFor="let s of filtered()"><td><strong>{{s.code}}</strong><br><small>{{s.name}}</small></td><td>{{s.brand_name}}<br>{{s.fuel_type}} · {{s.displacement_cc}}cc · {{s.cylinders}} cil.</td><td><span class="chip">{{s.sku_prefix||'sin prefijo'}}</span><br><small>{{s.equivalent_series||'Sin equivalentes'}}</small></td><td><button class="btn small" (click)="edit(s)">✏️</button></td></tr></tbody></table></div></article></section>
`})
export class InventoryEngineSeriesComponent{private http=inject(HttpClient);private route=inject(ActivatedRoute);items=signal<any[]>([]);search='';editing:any=null;nameTouched=false;form:any=this.blank();filtered=computed(()=>this.items().filter(s=>[s.code,s.name,s.brand_name,s.fuel_type,s.displacement_cc,s.equivalent_series].join(' ').toLowerCase().includes(this.search.toLowerCase())));constructor(){this.load();this.route.queryParamMap.subscribe(params=>{if(params.get('create')==='1')this.reset();});}blank(){return{code:'',name:'',brand_name:'',fuel_type:'',displacement_cc:'',cylinders:'',equivalent_series:'',sku_prefix:''};}load(){this.http.get<any[]>(`${API}/engine-series`).subscribe(v=>this.items.set(v));}onCodeChange(){if(!this.nameTouched)this.form.name=this.form.code; if(!this.form.sku_prefix)this.form.sku_prefix=String(this.form.code||'').toUpperCase();}autoFromCode(){this.form.name=this.form.code;this.form.sku_prefix=String(this.form.code||'').toUpperCase();this.nameTouched=false;}edit(s:any){this.editing=s;this.form={...this.blank(),...s};this.nameTouched=true;}reset(){this.editing=null;this.form=this.blank();this.nameTouched=false;}save(){if(!this.form.code){alert('Código requerido');return;}if(!this.form.name)this.form.name=this.form.code;if(!this.form.sku_prefix)this.form.sku_prefix=String(this.form.code).toUpperCase();const req=this.editing?this.http.put(`${API}/engine-series/${this.editing.id}`,this.form):this.http.post(`${API}/engine-series`,this.form);req.subscribe({next:()=>{this.reset();this.load();},error:e=>alert(e?.error?.detail||'No se pudo guardar')});}}
